# Generated by Django 3.0.2 on 2020-02-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0003_auto_20200202_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='slug',
        ),
    ]
